# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/click/extract-files.sh

# libgps is necessary to complete the compilation
PRODUCT_COPY_FILES += \
    device/htc/click/proprietary/librpc.so:obj/lib/librpc.so \
    device/htc/click/proprietary/libgps.so:obj/lib/libgps.so

# Proprietary stuff
PRODUCT_COPY_FILES += \
    device/htc/click/proprietary/akmd:system/bin/akmd \
    device/htc/click/proprietary/AudioPara4.csv:system/etc/AudioPara4.csv \
    device/htc/click/proprietary/AudioFilter.csv:system/etc/AudioFilter.csv \
    device/htc/click/proprietary/AudioPreProcess.csv:system/etc/AudioPreProcess.csv \
    device/htc/click/proprietary/libmm-qcamera-tgt.so:system/lib/libmm-qcamera-tgt.so \
    device/htc/click/proprietary/librpc.so:system/lib/librpc.so \
    device/htc/click/proprietary/libgps.so:system/lib/libgps.so \
    device/htc/click/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    device/htc/click/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    device/htc/click/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    device/htc/click/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    device/htc/click/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
    device/htc/click/proprietary/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    device/htc/click/proprietary/libhtc_ril.so:system/lib/libhtc_ril.so
